### ISSUE TITLE
cant build it

### ISSUE THREAD

**Issue by saiidabs** [wadie/ngx-font-size#1]
```
ERROR in ./node_modules/ngx-font-size/src/lib/ngx-font-size.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\source\Portal\node_modules\ngx-font-size\src\lib\ngx-font-size.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\source\Portal\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:913:23)
    at C:\source\Portal\node_modules\@ngtools\webpack\src\loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

im using 
Angular CLI: 8.3.29
Node: 12.11.1
OS: win32 x64
Angular: 8.2.14

**Comment by wadie** [comment]
Can you please share the content of your `tsconfig.app.json` file ?

**Comment by saiidabs** [comment]
@wadie 
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "esnext",
    "types": []
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}

```

@wadie any idea on how to fix it?

**Comment by wadie** [comment]
@saiidabs I just updated the package to be compatible with Angular 14. Do you still face the issue ?
